version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: config('DB_PASSWORD')
      MYSQL_DATABASE: config('DB_NAME')
      MYSQL_USER: config('DB_USER')
      MYSQL_PASSWORD: config('DB_PASSWORD')
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        mysql-network:
          aliases:
            - mysql
  python:
    build: .
    container_name: python
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
      driver: bridge
volumes:
  mysql-data:
      driver: local
